spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/jpa-data
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true

# 글로벌 페이징 설정
  data:
    web:
      pageable:
        default-page-size: 10
        max-page-size: 2000
        one-indexed-parameters: true # 페이지 파라미터가 1부터 시작함

logging.level:
  org.hibernate.SQL: debug
#  org.hibernate.type: trace
